var loadSpecs = {

    spain: {
        specs: [
            'spec/legislation/sections/document-structure/*_spec.js'
            //'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-first-import-and-duplicate-import-and-delete_spec.js',
            //'spec/legislation/sections/document-structure/right-panel-document-structure-Unit-Edition-Break-Line-Element-Add-Edit_spec.js',
           // 'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_spec.js',
        ]

    },

    mex: {
        specs: [

            //Havya specs
            'spec/legislation/sections/document-structure/document-structure-right-panel-UnitMenu-add-Unit-Structure-XML-word-file_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-UnitMenu-Add-Unit-Structure-XML-pdf-file_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-unit-menu-Add-unit-Structure-XML-Layout_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Legislation Unit Edition - Missing Table Element - Add - Clickinsert reference - Cancel button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-display-tree-report-aranzadi-RTF-and-PDF_spec.js',
            'spec/legislation/sections/document-structure/document-structure_unwrapping-notatexhist-listelement-repro_spec.js',
            'spec/legislation/sections/document-structure/document-structure_unwrapping-notatexthist-element-parrafo_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-first-import-and-duplicate-import-and-delete_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Add-Layout_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Edit-ItemizedList-Elements_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Edit-ListItem-Elements_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-legislation-unit-edition-item-list-element-edit-insert_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-legislation-unit-edition-missing-table-element-add-clicking-insert-reference -cancel-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-ordered-list-element-Add-Layout_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xlm-different-version_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xml-editor-legislation-unit-edition-clause-element-edit-layout-hover_spec.js',
            'spec/legislation/sections/document-structure/original-text-layout-for-loading-pdf-and-already-has-original-text_spec.js',
            'spec/legislation/sections/document-structure/original-text-layout-for-loading-the-first-original-text_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-cancel_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-loading-a-file-different-from-pdf-not-possible_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-and-basic-layout-displaymode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-and-basic-layout-editmode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-duplicate-structure-date_create-and-delete.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Edit-Layer-XML-Editor-Layout_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xeditor-added-as-child-button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xeditor-layout-and-cancel-button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xml-added-as-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xml-cancel-and-close-buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-dropdown_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Unit-Edition-Break-Line-Element-Add-Edit_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-switch-among-different-document-structures-medium-version_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-switch-among-different-document-structures-original-version_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Strikethrough_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-delete-a-unit-from-structure-delete-a-unit-with-versions-error_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Subscript_spec.js',
            'spec/legislation/sections/document-structure/right-panel-original-text-delete-original-cancel_spec.js',
            'spec/legislation/sections/document-structure/right-panel-initial-content-edit-mode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-initial-content-display-mode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-view-several-versions_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-view-original-version_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-view-navigation-buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-view-content_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-rename-nice-to-have-valid-and-invalid-unit-no-part_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-rename-nice-to-have-empty_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-delete-a-unit-from-structure-delete-a-branch-unit-error_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xml-cancel-and-close-buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-upper-sibling_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Underline_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Superscript_spec.js',
            'spec/legislation/sections/document-structure/document-structure_borrar_dir_element_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-Borrar-numparagraph-falta.figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-falta.table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-Borrar-numparagraph-figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-itemizedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-orderedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-paragraph-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-parrafo-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-unidad-child_spec.js',
            'spec/legislation/sections/document-structure/rightpanel-document-structure-xeditor-Borrar-nota-element_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numbaragraph-element-falta.figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numbaragraph-element-figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numparagraph-element-itemizedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-falta.table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-nota.texto-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numparagraph-element-orderedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-paragraph-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-parrafo-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-unidad-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-eliminar-numparagraph-element-Repro-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-eliminar-numparagraph-table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-eliminar_dir_element_spec.js',
            'spec/legislation/sections/document-structure/rightpanel-document-structure-xeditor-eliminar-nota-element_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-bold-plus-italics-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-editor-aranzadi-changes-history-empty_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0 Editor-Aranzadi-Changes history_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-lower-cases-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Overline-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-add-1.0-Editor-aranzadi-paragraph-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Strikethrough-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Underline-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-upper-cases-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-add-1.0-editor-aranzadi-validations-pass-or-fail_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor -Aranzadi-Inconstitucional_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Angle quote button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Bold button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Clause_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Default XML elements&Buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Derogado_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Destacado_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Default XML elements&Buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Edit layer with XML_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Element selector_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Ementa_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Empty search button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Espaciado (Spacing)_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Fecha_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Imagen_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Italic button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Llamada a nota_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Paragraph_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Recomendaciones_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Replace all button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Replace button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Resumen de Resumen_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Search button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Subscript button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Texto de nota_spec.js',


            //kavitha spec

            'spec/legislation/sections/document-structure/document-structure-Copy external text - Verify XML code _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-1-Unit-edition_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-Paragraphs-styles-Unit-creation-Verify elements _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copyexternaltext-2-Abstract-Edition_spec.js',

            'spec/legislation/sections/document-structure/document-structure- Legislation-Unit-Edition-Missing-Image-Element-Edit _spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-copy-externalText-tables-wordFormat-unitCreation_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-unit-menu-add-unit-structure-XML-duplicated-Fails_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-unit-menu-add-Unit-Structure-XML-Added-upper-sibling_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-unit-menu-add-unit-structure-XML-Added-lower sibling_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-unit-menu-Add-Unit-Structure using XML-added-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Unwrapping-Itemized-List-Element-with-listem_spec.js',

            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-AN_unit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-CI_unit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-R_unit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-Th_unit_spec.JS',
            'spec/legislation/sections/document-structure/document-structure-Copy external text - Verify XML code _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-1-Unit-edition_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-Paragraphs-styles-Unit-creation-Verify elements _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copyexternaltext-2-Abstract-Edition_spec.js',


            //sai specs
            'spec/legislation/sections/document-structure/document-structure-xEditor-Delete-notatexto-elements-Unwrapping-with-children_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-notatexthist-element-table_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-notatexthist-element-parrafo_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-Notatexthist-Element-Falta.table_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-Itemized-List-Element-Capatexto_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-MainMenu-Add-Unit-Structure-XML-Full-document-load-Fails_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Right Panel-UnitMenu-Add-Unit-Structure-XML-Full-document-load-Fails_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Right Panel-UnitMenu-Add-Unit-Structure-XML-Full-document-load-Fails_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Right Panel-Unit Menu-Add-Unit-Structure-XML-Added-upper-sibling_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Paste external text_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Edit a unit-shows display expanded_spec.js',
            'spec/legislation/sections/document-structure/document-structure-document-XML-language2_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Delete-OrderedList-Element-Capatexto_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Delete-a-unit-with-versions-Error_spec.js',
            'spec/legislation/sections/document-structure/document-structure-click cancel-Select-unit-delete-from-dropdown.js',
            'spec/legislation/sections/document-structure/document-structure-Cancel-deletion-of-the-layer_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Aranzadi-Create new unit from another article as child _spec.js'



        ]
    },




    gulf: {
        specs: [

            'spec/legislation/sections/document-structure/document-structure_unwrapping-notatexhist-listelement-repro_spec.js',
            'spec/legislation/sections/document-structure/document-structure_unwrapping-notatexthist-element-parrafo_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xml-cancel-and-close-buttons_spec.js',
            'spec/legislation/sections/document-structure/document-structure-document-XML-language2_spec.js',
            'spec/legislation/sections/document-structure/document-structure-display-tree-report-aranzadi-RTF-and-PDF_spec.js',
            'spec/legislation/sections/document-structure/document-structure- Legislation-Unit-Edition-Missing-Image-Element-Edit _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-editor-aranzadi-changes-history-empty_spec.js',
            'spec/legislation/sections/document-structure/document-structure_borrar_dir_element_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy external text - Verify XML code _spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-UnitMenu-Add-Unit-Structure-XML-pdf-file_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-UnitMenu-add-Unit-Structure-XML-word-file_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Cancel-deletion-of-the-layer_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-1-Unit-edition_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-Paragraphs-styles-Unit-creation-Verify elements _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copyexternaltext-2-Abstract-Edition_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Delete-OrderedList-Element-Capatexto_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Legislation Unit Edition - Missing Table Element - Add - Clickinsert reference - Cancel button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Legislation-Unit-Edition-Item-List-Element-Edit-Insert_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Legislation-Unit-Edition-Item-List-Element-Edit-ListItem-Elements_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Paste external text_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Unwrapping-Itemized-List-Element-with-listem_spec.js',
            
            
            'spec/legislation/sections/document-structure/document-structure-xEditor-Borrar-numparagraph-falta.figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-falta.table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-Borrar-numparagraph-figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-itemizedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Xeditor-borrar-numparagraph-notatexto-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-orderedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-paragraph-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-parrafo-child_spec.js',
            
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numbaragraph-element-falta.figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numbaragraph-element-figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-falta.table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numparagraph-element-itemizedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-nota.texto-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numparagraph-element-orderedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-paragraph-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-parrafo-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-unidad-child_spec.js',
            
            'spec/legislation/sections/document-structure/document-structure-xEditor-ordered-list-element-Add-Layout_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Edit-ListItem-Elements_spec',
            'spec/legislation/sections/document-structure/document-structure-xEditor-legislation-unit-edition-item-list-element-edit-insert_spec.js',
            
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor -Aranzadi-Inconstitucional_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Clause_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Default XML elements&Buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Angle quote button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Bold button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Derogado_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Destacado_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Espaciado (Spacing)_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Fecha_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Italic button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Llamada a nota_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Paragraph_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Replace all button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Resumen de Resumen_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Subscript button_spec.js',
            
            'spec/legislation/sections/document-structure/right-panel-document-structure-and-basic-layout-displaymode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-and-basic-layout-editmode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Edit-Layer-XML-Editor-Layout_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-eliminar-numparagraph-element-Repro-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-eliminar-numparagraph-table-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xeditor-added-as-child-button_spec.js',
            
            
            
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-bold-plus-italics-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Changes-history_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-editor-aranzadi-changes-history-empty_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-lower-cases-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Overline-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-1.0-Editor-aranzadi-paragraph-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Strikethrough-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Underline-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-upper-cases-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-1.0-editor-aranzadi-validations-pass-or-fail_spec.js',
            
            
            'spec/legislation/sections/document-structure/right-panel-original-text-delete-original-cancel_spec.js',
            'spec/legislation/sections/document-structure/right-panel-initial-content-edit-mode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-initial-content-display-mode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-view-original-version_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-rename-nice-to-have-valid-and-invalid-unit-no-part_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-rename-nice-to-have-empty_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-delete-a-unit-from-structure-delete-a-branch-unit-error_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xml-cancel-and-close-buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-upper-sibling_spec.js',
            
            'spec/legislation/sections/document-structure/right-panel-unwrrapping-Math-Element-with-mathsubindex_spec.js',
            'spec/legislation/sections/document-structure/right-panel-unwrapping-math-sub-section-deleting-mathsubsup_spec.js',
            ////  'spec/legislation/sections/document-structure/right-panel-document-structure-Unit-Edition-Break-Line-Element-Add-Edit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Aranzadi-Create new unit from another article as child _spec.js',
            'spec/legislation/sections/document-structure/document-structure-click cancel-Select-unit-delete-from-dropdown.js',
            
            
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-Itemized-List-Element-Capatexto_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xml-editor-legislation-unit-edition-clause-element-edit-layout-hover_spec.js',
            'spec/legislation/sections/document-structure/original-text-layout-for-loading-pdf-and-already-has-original-text_spec.js',
            'spec/legislation/sections/document-structure/original-text-layout-for-loading-the-first-original-text_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-cancel_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-first-import-and-duplicate-import-and-delete_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-loading-a-file-different-from-pdf-not-possible_spec.js',
            'spec/legislation/sections/document-structure/document-structure-click cancel-Select-unit-delete-from-dropdown.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Texto de nota_spec.js',
            
        ]

    },

    br: {
        specs: [
          
           'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-bold-plus-italics-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-editor-aranzadi-changes-history-empty_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-lower-cases-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Overline-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-add-1.0-Editor-aranzadi-paragraph-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Strikethrough-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-Underline-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-Add-1.0-Editor-Aranzadi-upper-cases-button_spec_ie.js',
            'spec/legislation/sections/document-structure/document-structure-add-1.0-editor-aranzadi-validations-pass-or-fail_spec.js',

            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-AN_unit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-CI_unit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-R_unit_spec.js',
            'spec/legislation/sections/document-structure/document-structure-add-analysis(CI, AN,Th, R)-Th_unit_spec.js',

            'spec/legislation/sections/document-structure/document-structure-Aranzadi-Create new unit from another article as child _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Cancel-deletion-of-the-layer_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-1-Unit-edition_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-Paragraphs-styles-Unit edition-Verify XML code_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copy-external-text-Paragraphs-styles-Unit-creation-Verify elements _spec.js',
            'spec/legislation/sections/document-structure/document-structure-Copyexternaltext-2-Abstract-Edition_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Delete-a-unit-with-versions-Error_spec.js',

            'spec/legislation/sections/document-structure/document-structure-Legislation Unit Edition - Missing Table Element - Add - Clickinsert reference - Cancel button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Legislation-Unit-Edition-Item-List-Element-Edit-Insert_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Legislation-Unit-Edition-Item-List-Element-Edit-ListItem-Elements_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Paste external text_spec.js',

            'spec/legislation/sections/document-structure/document-structure-Right Panel-Unit Menu-Add-Unit-Structure-XML-Added-upper-sibling_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Right Panel-UnitMenu-Add-Unit-Structure-XML-Full-document-load-Fails_spec.js',
           // 'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-MainMenu-Add-Unit-Structure-XML-Full-document-load-Fails_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-unit-menu-Add-Unit-Structure using XML-added-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-unit-menu-add-unit-structure-XML-Added-lower sibling_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-document-structure-unit-menu-add-Unit-Structure-XML-Added-upper-sibling_spec.js',

            'spec/legislation/sections/document-structure/document-structure-right-panel-unit-menu-add-unit-structure-XML-duplicated-Fails_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-unit-menu-Add-unit-Structure-XML-Layout_spec.js',
            'spec/legislation/sections/document-structure/document-structure-right-panel-UnitMenu-Add-Unit-Structure-XML-pdf-file_spec.js',
            'spec/legislation/sections/document-structure/document-structure-click cancel-Select-unit-delete-from-dropdown_spec.js',

            'spec/legislation/sections/document-structure/document-structure-xEditor-Delete-notatexto-elements-Unwrapping-with-children_spec.js',
            'spec/legislation/sections/document-structure/document-structure-Xeditor-borrar-munparagraph-nota.texto-child_spec-ie.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparaghaph-element-HR-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-Borrar-numparagraph-falta.figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-falta.table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-Borrar-numparagraph-figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-itemizedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-orderedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-paragraph-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-parrafo-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-borrar-numparagraph-unidad-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-Itemized-List-Element-Capatexto_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-Notatexthist-Element-Falta.table_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-notatexthist-element-parrafo_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-delete-notatexthist-element-table_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numbaragraph-element-falta.figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numbaragraph-element-figura-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparaghap-element-HR-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numparagraph-element- itemizedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-falta.table-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-nota.texto-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xeditor-eliminar-numparagraph-element-orderedlist-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-paragraph-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-parrafo-child_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-eliminar-numparagraph-element-unidad-child_spec.js',
           // 'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Add-Layout_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Edit-ItemizedList-Elements_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-item-list-element-Edit-ListItem-Elements_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-legislation-unit-edition-item-list-element-edit-insert_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-Legislation-Unit-Edition-Missing-Image-Element-Add-Clicking-insert-reference_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-legislation-unit-edition-missing-table-element -Add-Clicking-insert-reference-cancel-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-legislation-unit-edition-missing-table-element-add-clicking-insert-reference -cancel-button_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xEditor-ordered-list-element-Add-Layout_spec.js',
           // 'spec/legislation/sections/document-structure/document-structure-xlm-different-version_spec.js',
            'spec/legislation/sections/document-structure/document-structure-xml-editor-legislation-unit-edition-clause-element-edit-layout-hover_spec.js',
            'spec/legislation/sections/document-structure/editorial-notes-copy-external-text_spec.js',

            'spec/legislation/sections/document-structure/original-text-layout-for-loading-pdf-and-already-has-original-text_spec.js',
            'spec/legislation/sections/document-structure/original-text-layout-for-loading-the-first-original-text_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-cancel_spec.js',
            'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-first-import-and-duplicate-import-and-delete_spec.js',
           // 'spec/legislation/sections/document-structure/original-text-loading-the-original-text-by-using-import-loading-a-file-different-from-pdf-not-possible_spec.js',

            'spec/legislation/sections/document-structure/right-Panel-document Structure-Main Menu-Add a Unit from Structure using Xeditor-Layout.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor -Aranzadi-Inconstitucional_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi -Subscript button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Angle quote button_spec_ie.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Bold button_spec_ie.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Clause_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-copy-and-paste-buttons_spec_ie.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-cut-and-paste-buttons_spec_ie.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Default XML elements&Buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Derogado_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Destacado_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Edit layer with XML_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Element selector_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Ementa_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Empty search button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Espaciado (Spacing)_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Fecha_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Imagen_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Italic button_spec_ie.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Llamada a nota_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Paragraph_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Recomendaciones_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Replace all button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Replace button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Resumen de Resumen_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Search button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Add 1.0 Editor-Aranzadi-Texto de nota_spec.js',

            'spec/legislation/sections/document-structure/right-panel-document-structure-and-basic-layout-displaymode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-and-basic-layout-editmode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-duplicate-structure-date_create-and-delete_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-eliminar-numparagraph-element-Repro-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-eliminar-numparagraph-table-child_spec.js',

            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xeditor-added-as-child-button_spec.js',
            //'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xeditor-layout-and-cancel-button_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xml-added-as-child_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-add-a-unit-from-structure-using-xml-cancel-and-close-buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-main-menu-dropdown_spec.js',

            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Strikethrough_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Subscript_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Superscript_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-lower-sibling_Underline_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xeditor-added-as-upper-sibling_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-add-a-unit-from-structure-using-xml-cancel-and-close-buttons_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-delete-a-unit-from-structure-delete-a-branch-unit-error_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-delete-a-unit-from-structure-delete-a-unit-with-versions-error_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-rename-nice-to-have-empty_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-unit-menu-rename-nice-to-have-valid-and-invalid-unit-no-part_spec.js',

            'spec/legislation/sections/document-structure/right-panel-document-structure-Edit-Layer-XML-Editor-Layout_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-view-original-version_spec.js',
            'spec/legislation/sections/document-structure/right-panel-initial-content-display-mode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-initial-content-edit-mode_spec.js',
            'spec/legislation/sections/document-structure/right-panel-original-text-delete-original-cancel_spec.js',
            'spec/legislation/sections/document-structure/right-panel-unwrapping-math-sub-section-deleting-mathsubsup_spec.js',
            'spec/legislation/sections/document-structure/right-panel-Unwrapping-Notatexhist-List-Element-with-Repro_spec.js',
            'spec/legislation/sections/document-structure/right-panel-document-structure-Unit-Edition-Break-Line-Element-Add-Edit_spec.js',
            'spec/legislation/sections/document-structure/right-panel-unwrrapping-Math-Element-with-mathsubindex_spec.js',

        ]
    },

}
module.exports = loadSpecs;