var loadSpecs = {

    spain: {
        specs: [

             'spec/legislation/sections/relationship-section/*_spec.js',
            //'spec/legislation/sections/relationship-section/Relationships-GCMSNXT-5676-Relationships-Add from text icons-from document level-lamp-new_spec.js',
        ]
    },

    mex: {
        specs: [

            //havya
            'spec/legislation/sections/relationship-section/add-duplicate-relationship_spec.js',
            'spec/legislation/sections/relationship-section/Add-multple-tags-Relationships-Support-range-creation-Multiple-selection-units_spec.js',
            'spec/legislation/sections/relationship-section/add-new-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-product-for-relationships-from-multiple-pages_spec.js',
            'spec/legislation/sections/relationship-section/add-new-and-then-copy-the-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-and-Add-10-products-and-10-relationships_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-and-Add_new_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-Cancel-and-Close-button_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-Layout_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-ProductList_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-many-and-delete-in-consolidation-search-table_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-one-and-delete-in-consolidation-search-table-row_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Adapta_spec.js',

            'spec/legislation/sections/relationship-section/add-relationship-type-Adopta_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Declara-carácter-básico_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Declara-carácter-no-básico_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Incorpora_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Transpone_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Acepta-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Acepta-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Adhiere-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Adhiere-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-ampliaPlazo-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Aprueba-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Aprueba-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-entradaEnVigor-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-prorroga-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Ratifica-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Ratifica-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-with-compliance-document_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-with-wrong-margin_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-with-wrong-type_spec.js',

            'spec/legislation/sections/relationship-section/add-single-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-single-relationship-from-table_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Annotations_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Annotations-by-source-and-target_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Consolidations_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Consolidations-by-source-and-target_spec.js',
            'spec/legislation/sections/relationship-section/copy-relationship-source_spec.js',
            'spec/legislation/sections/relationship-section/create-a-non-consolidated-relationship-and-edit_spec.js',


            'spec/legislation/sections/relationship-section/edit-open-a-set-of-non-consolidated-relationships_spec.js',
            'spec/legislation/sections/relationship-section/edit-open-a-set-of-relationships-consolidated_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Document-Structure-being-selectable-Aranzadi-Layout_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Document-Structure-being-selectable-Aranzadi-Structure_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Modify-product-for-relationships-from-multiple-pages_new_spec.js',

            'spec/legislation/sections/relationship-section/Relationship-Edit-relationship Renumera-Not-Consolidated-Change-fields-Target-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Edit-relationship-Renumera - Not-Consolidated - Change-fields-relationship-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Edit-relationship-Renumera-Consolidated-Edit-fields-Relationship-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-relationship-Renumera-new_spec.js',
            'spec/legislation/sections/relationship-section/Search of relationships - run the search and go to the result list - Marginal2_spec.js',

            //Roja specs

            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-No-newer-versions-consolidated-pointing-same-amended-unit-date-of-new-version-later_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-No-newer-versions-Relationships-consolidated-amended-document-date-of-new-version_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-Older-relationship-consolidate-current-pointing-amended-unit-older-pointing-amended-document_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-Older-relationship-pending-consolidate-current-pointing-amended-unit-ancestor-current-amended-unit_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-Older-relationship-pending-consolidate-current-pointing-amended-unit-older-pointing-same-amended-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter_sourcedate_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter-source_unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter-target-date_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-Type-Relationship-Consolidated-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Edit-Type-Relationship-Not-Consolidated-new_spec.js',
            'spec/legislation/sections/relationship-section/relationships-EDIT-Vigencias-No-Incorporada-new_spec.js',

            //kavitha specs

            'spec/legislation/sections/relationship-section/relationship-edit-section-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-source-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-target-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edition-of-an-existing-one-Target-Level_spec.js',
            'spec/legislation/sections/relationship-section/relationshipfilter-consolidated_spec.js',
            'spec/legislation/sections/relationship-section/relationshipfilter-relationship_type_spec.js',
            'spec/legislation/sections/relationship-section/Relationships - Actions in Relationships table - Delete Many Entries - Try to select consolidated multiple relationships-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships - Actions in Relationships table - Delete One Entry - 23 07 2010 - Delete Modifica relationship-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Add Relationships-Missing-unit-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Add-declara-mantenimiento-en-vigor-hasta-new_spec.js',

            //shriya specs

            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Add-and-Remove-Products_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Add-n-Products_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Layout-ProductTab_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-ProductList_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Duplicated-relationship-error-new_spec.js',


            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-beteween-legis-and-other-kind_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-creation-by-dif-version_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-creation-changing-target-by-source_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Add-rotate_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Consolidations_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Current-Marginal_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-icons_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-invalid-marginal-eye_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Saved-Relationship_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-edit-add-a-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-edit-existing-relationship_destination_spec.js',
            'spec/legislation/sections/relationship-section/relationship-edit-existing-relationship_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Remove-several-Products-from-several-Relationships_new_spec.js',

            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-paragraphIds-empty-levelInciso_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Plus-button-inside-popup_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Range-of-units-from-source_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Range-of-units-from-target_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Edit-and-add-more-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Multiple-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-No-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Remove-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-verify-multiple-level-seccion_spec.js',
            'spec/legislation/sections/relationship-section/relationship-with-delete-button-disabled_spec.js',
            'spec/legislation/sections/relationship-section/relationship-without-products-and-remove-unique-product_new_spec.js',




            //'spec/legislation/sections/relationship-section/Search of relationships - run the search and go to the result list3_spec.js'
        ]
    },

    br: {
        specs: [
            //Not Available

            'spec/legislation/sections/relationship-section/add-duplicate-relationship_spec.js',
            'spec/legislation/sections/relationship-section/Add-multple-tags-Relationships-Support-range-creation-Multiple-selection-units_spec.js',
            'spec/legislation/sections/relationship-section/add-new-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-and-Add-10-products-and-10-relationships_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-Cancel-and-Close-button_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-Layout_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-ProductList_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Adapta_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Adopta_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Declara-carácter-básico_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Declara-carácter-no-básico_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Incorpora_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-type-Transpone_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Acepta-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Acepta-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Adhiere-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Consolidations-by-source-and-target_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Current-Marginal_new_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-ampliaPlazo-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Aprueba-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Aprueba-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-entradaEnVigor-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-prorroga-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Ratifica-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Ratifica-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-single-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-single-relationship-from-table_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-with-compliance-document_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-with-wrong-margin_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Annotations_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Annotations-by-source-and-target_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Consolidations_spec.js',
            'spec/legislation/sections/relationship-section/copy-relationship-source_spec.js',
            'spec/legislation/sections/relationship-section/create-a-non-consolidated-relationship-and-edit_spec.js',
            'spec/legislation/sections/relationship-section/edit-open-a-set-of-consolidated-relationships_spec.js',
            'spec/legislation/sections/relationship-section/modify-relationship-and-verify-error-for-Consolidated_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Document-Structure-being-selectable-Aranzadi-Layout_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Document-Structure-being-selectable-Aranzadi-Structure_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Add-rotate_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-enabled_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-icons_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-invalid-marginal-eye_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-relationship-Renumera-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Edit-relationship Renumera-Not-Consolidated-Change-fields-Target-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-source-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-target-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-Type-Relationship-Consolidated-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edition-of-an-existing-one-Target-Level_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter_sourcedate_spec.js',
            'spec/legislation/sections/relationship-section/add-product-for-relationships-from-multiple-pages_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-and-Add_new_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Adhiere-Creation_spec.js',
            'spec/legislation/sections/relationship-section/copy-relationship-for-different-types_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Consolidations_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-creation-changing-target-by-source_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Add-and-Remove-Products_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Add-n-Products_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Layout-ProductTab_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-ProductList_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-beteween-legis-and-other-kind_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-creation-by-dif-version_new_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-No-newer-versions-consolidated-pointing-same-amended-unit-date-of-new-version-later_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-No-newer-versions-Relationships-consolidated-amended-document-date-of-new-version_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-Older-relationship-consolidate-current-pointing-amended-unit-older-pointing-amended-document_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-Older-relationship-pending-consolidate-current-pointing-amended-unit-ancestor-current-amended-unit_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-Older-relationship-pending-consolidate-current-pointing-amended-unit-older-pointing-same-amended-unit_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Edit-relationship-Renumera - Not-Consolidated - Change-fields-relationship-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Edit-relationship-Renumera-Consolidated-Edit-fields-Relationship-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-edit-section-new_spec.js',
            'spec/legislation/sections/relationship-section/create-a-non-consolidated-relationship-and-edit_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-one-and-delete-in-consolidation-search-table-row_spec.js',
            'spec/legislation/sections/relationship-section/edit-open-a-set-of-non-consolidated-relationships_spec.js',
            'spec/legislation/sections/relationship-section/edit-open-a-set-of-relationships-consolidated_spec.js',
            'spec/legislation/sections/relationship-section/relationship-edit-existing-relationship_destination_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Duplicated-relationship-error-new_spec.js',

            'spec/legislation/sections/relationship-section/relationship-filter-source_unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Modify-product-for-relationships-from-multiple-pages_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Remove-several-Products-from-several-Relationships_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-selection-through-the-pages_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-sumarization-document-relationships-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-summarization-documents-annotation-consolidation-relationships-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-paragraphIds-empty-levelInciso_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Plus-button-inside-popup_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Range-of-units-from-source_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Range-of-units-from-target_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Edit-and-add-more-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Multiple-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-No-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Remove-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-verify-multiple-level-seccion_spec.js',
            'spec/legislation/sections/relationship-section/relationship-with-delete-button-disabled_spec.js',
            'spec/legislation/sections/relationship-section/relationship-without-products-and-remove-unique-product_new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Add Relationships-Missing-unit-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Add-declara-mantenimiento-en-vigor-hasta-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Add-Relationships-Add-unit-unit-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-clear-target-form_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Copy-relationship-target-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-COPY-Vigencias-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-EDIT-Anotaciones-user-Analista-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Edit-Type-Relationship-Not-Consolidated-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Edition of an existing one-Relationship note_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Relationships-Add-Relationships-Mandatory-fields-red-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Support-range-creation-Multiple-selection-units-Relationship-creation-Range-source-layer_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-table-View-new_spec.js',
            'spec/legislation/sections/relationship-section/Remove-tags-Relationships-Support-range-creation-Multiple-selection-units_spec.js',
        ]
    },

    gulf: {
        specs: [
            //****** */do not distrub below spec files****//
            'spec/legislation/sections/relationship-section/add-duplicate-relationship_spec.js',
            'spec/legislation/sections/relationship-section/Add-multple-tags-Relationships-Support-range-creation-Multiple-selection-units_spec.js',
            'spec/legislation/sections/relationship-section/add-new-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-product-for-relationships-from-multiple-pages_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-and-Add_new_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-and-Add-10-products-and-10-relationships_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-Cancel-and-Close-button_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-Layout_spec.js',
            'spec/legislation/sections/relationship-section/add-product-massive-verify-Display-ProductList_spec.js',
            'spec/legislation/sections/relationship-section/add-relationship-and-consolidate-and-delete-in-consolidation-search_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Acepta-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Acepta-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Adhiere-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Adhiere-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Aprueba-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Aprueba-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-entradaEnVigor-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-prorroga-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Ratifica-Creation_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-type-Ratifica-Required-fields_spec.js',
            'spec/legislation/sections/relationship-section/add-Relationships-with-wrong-margin_spec.js',
            'spec/legislation/sections/relationship-section/add-single-relationship_spec.js',
            'spec/legislation/sections/relationship-section/add-single-relationship-from-table_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Annotations_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Annotations-by-source-and-target_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Consolidations_spec.js',
            'spec/legislation/sections/relationship-section/check-the-order-data-retrieved-Consolidations-by-source-and-target_spec.js',
            'spec/legislation/sections/relationship-section/copy-relationship-for-different-types_spec.js',
            'spec/legislation/sections/relationship-section/copy-relationship-source_spec.js',
            'spec/legislation/sections/relationship-section/create-a-non-consolidated-relationship-and-edit_spec.js',
            'spec/legislation/sections/relationship-section/edit-relationship-language_spec.js',
            'spec/legislation/sections/relationship-section/modify-relationship-and-verify-error-for-Consolidated_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Document-Structure-being-selectable-Aranzadi-Layout_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Document-Structure-being-selectable-Aranzadi-Structure_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Tree-report-Aranzadi-Layout-ProductTab_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-beteween-legis-and-other-kind_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Display-Unit-Text-on-relationships-creation-by-dif-version_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Add-rotate_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Documents-rotation-Consolidations_new_spec.js',
             'spec/legislation/sections/relationship-section/relationship-Edit-source-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-target-unit_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-Type-Relationship-Consolidated-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edit-Type-Relationship-Not-Consolidated-new_spec.js',
            'spec/legislation/sections/relationship-section/relationships-EDIT-Vigencias-No-Incorporada-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Edition-of-an-existing-one-Target-Level_spec.js',
            'spec/legislation/sections/relationship-section/Relationship-Ensure-chronological-order-No-newer-versions-consolidated-pointing-same-amended-unit-date-of-new-version-later-date-of-effect-current-relationship_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter-source_doucment_spec.js',
            'spec/legislation/sections/relationship-section/relationship-filter-target-date_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Modify-product-for-relationships-from-multiple-pages_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-multilingual-edit-fields-global-icon-nivel-fields_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Multilingual-support-Default-Language_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Multilingual-support-Delete-languages-added_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Multilingual-support-Delete-languages-in-grayness-inside-the-dropdown_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Multilingual-support-Edit-fields-from-global-icon-Nota-field_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Not-Consolidated-one_spec.js',
            'spec/legislation/sections/relationship-section/relationship-selection-through-the-pages_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-sumarization-document-relationships-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-summarization-documents-annotation-consolidation-relationships-new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-paragraphIds-empty-levelInciso_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Plus-button-inside-popup_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Range-of-units-from-source_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-creation-Range-of-units-from-target_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Edit-and-add-more-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Multiple-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-No-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-Support-relationship-range-creation-Multiple-levels-sections-Remove-paragraph-id_new_spec.js',
            'spec/legislation/sections/relationship-section/relationship-verify-multiple-level-seccion_spec.js',
            'spec/legislation/sections/relationship-section/relationship-with-delete-button-disabled_spec_b000.js',
            'spec/legislation/sections/relationship-section/relationship-without-products-and-remove-unique-product_new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Add Relationships-Missing-unit-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-GCMSNXT-5676-Relationships-Add from text icons-from document level-lamp-new_spec.js',
            'spec/legislation/sections/relationship-section/Relationships-Support-range-creation-Multiple-selection-units-Relationship-creation-Range-target-layer_spec.js',
            'spec/legislation/sections/relationship-section/Remove-tags-Relationships-Support-range-creation-Multiple-selection-units_spec.js',

        ]
    },

}
module.exports = loadSpecs;